FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir streamlit pyhive pandas plotly thrift thrift-sasl

# Copy the application code
COPY streamlit/ /app/

# Expose the default Streamlit port
EXPOSE 8501

# Use CMD to run the Streamlit application
CMD ["streamlit", "run", "app_complete.py", "--server.port=8501", "--server.address=0.0.0.0"]